print("*****************")
a=input("학생 이름은?")
b=input("국어 점수는?")
c=input("영어 점수는?")
d=input("수학 점수는?")
print("=======================")
print(a," ","총점과 평균입니다.")
print("총점=",int(b)+int(c)+int(d))
print("평균=",(int(b)+int(c)+int(d))/3)
print("우왕 올백이야!")
